### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by decima** [decima/kip#22] opened 2020-02-29 16:32 UTC
We need the following permissions : 
- Read the KB
  - Public or Authenticated
- Write in the KB
  - Authenticated

Maybe add roles ? Keep in mind that we'll have to implement also #20 

- [ ] Specs of the permission
- [ ] Implementation

**Comment by monvoisinf** [comment] 2020-04-14 14:16
Duplicate of the issue #38

**Closed as completed** 2020-04-14 14:15 UTC
Labels: duplicate
